// data/sessionsData.js
const sessionsData = [
  {
    id: 1,
    title: "Advanced Algorithm Design",
    batch: "Batch 2024A",
    subject: "DSA",
    date: "2025-02-10",
    time: "2:00 PM",
    duration: "1h 30m",
    instructor: "Dr. Sarah Chen",
    resources: [
      "https://courses.cs.duke.edu/fall08/cps230/Book.pdf", // PDF link from Duke Computer Science
      "https://github.com/algorithm-archive/algorithm-archive",
    ],
    courseName: "Advanced DSA",
    status: "Upcoming",
  },
  {
    id: 2,
    title: "Database Systems",
    batch: "Batch 2024B",
    subject: "DB",
    date: "2025-02-11",
    time: "10:00 AM",
    duration: "1h 30m",
    instructor: "Prof. Michael Rodriguez",
    resources: [
      "https://www.w3schools.com/sql/",
      "https://www.lucidchart.com/pages/database-diagram/database-schema",
    ],
    courseName: "Database Management",
    status: "Past",
  },
  {
    id: 3,
    title: "Web Development Workshop",
    batch: "Batch 2024C",
    subject: "Coding",
    date: "2025-02-12",
    time: "3:00 PM",
    duration: "1h 30m",
    instructor: "Emily Johnson",
    resources: [
      "https://developer.mozilla.org/en-US/docs/Learn/HTML",
      "https://github.com/mdn",
    ],
    courseName: "Full Stack Web Development",
    status: "Past",
  },
  {
    id: 4,
    title: "AI Fundamentals",
    batch: "Batch 2024D",
    subject: "ML101",
    date: "2025-02-13",
    time: "11:00 AM",
    duration: "1h 30m",
    instructor: "Dr. Lisa Park",
    resources: [
      "https://www.ibm.com/cloud/learn/what-is-artificial-intelligence",
      "https://jupyter.org/",
    ],
    courseName: "Introduction to AI",
    status: "Upcoming",
  },
  {
    id: 5,
    title: "Mobile App Development",
    batch: "Batch 2024E",
    subject: "General",
    date: "2025-02-14",
    time: "1:00 PM",
    duration: "1h 30m",
    instructor: "James Wilson",
    resources: [
      "https://reactnative.dev/docs/getting-started",
      "https://github.com/facebook/react-native",
    ],
    courseName: "Mobile Development",
    status: "Upcoming",
  },
  {
    id: 6,
    title: "Network Security",
    batch: "Batch 2024F",
    subject: "CSBT",
    date: "2025-02-15",
    time: "9:00 AM",
    duration: "1h 30m",
    instructor: "Robert Martinez",
    resources: [
      "https://www.cisco.com/c/en/us/products/security/what-is-cybersecurity.html",
      "https://www.cisco.com/c/en/us/support/security/firewall-products/tsd-products-support-series-home.html",
    ],
    courseName: "Cybersecurity Basics",
    status: "Upcoming",
  },
  {
    id: 7,
    title: "Python Programming Basics",
    batch: "Batch 2024G",
    subject: "Coding",
    date: "2025-02-16",
    time: "1:00 PM",
    duration: "1h 30m",
    instructor: "Alex Thompson",
    resources: [
      "https://docs.python.org/3/tutorial/",
      "https://www.hackerrank.com/domains/python",
    ],
    courseName: "Introduction to Python",
    status: "Upcoming",
  },
  {
    id: 8,
    title: "Software Architecture",
    batch: "Batch 2024H",
    subject: "General",
    date: "2025-02-17",
    time: "11:00 AM",
    duration: "1h 30m",
    instructor: "Dr. David Kim",
    resources: [
      "https://www.oreilly.com/library/view/design-patterns-elements/0201633612/",
      "https://www.uml-diagrams.org/",
    ],
    courseName: "Software Engineering",
    status: "Upcoming",
  },
  {
    id: 9,
    title: "Data Structures Revision",
    batch: "Batch 2024I",
    subject: "Revision",
    date: "2025-02-10",
    time: "01:59 AM",
    duration: "0h 1m",
    instructor: "Alex Thompson",
    resources: [
      "https://www.bigocheatsheet.com/",
      "https://www.hackerrank.com/",
    ],
    courseName: "Data Structures & Algorithms",
    status: "Upcoming",
  },
  {
    id: 10,
    title: "Advanced Software Architecture",
    batch: "Batch 2024J",
    subject: "SDET",
    date: "2025-02-19",
    time: "11:00 AM",
    duration: "1h 30m",
    instructor: "Dr. David Kim",
    resources: [
      "https://microservices.io/",
      "https://github.com/donnemartin/system-design-primer",
    ],
    courseName: "Software Development & Testing",
    status: "Upcoming",
  },
];

export default sessionsData;
